# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/jl
    steps:
      - checkout
      - run: mkdir -p out
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: GOOS=windows GOARCH=amd64 go build -o out/jl.exe cmd/jl/main.go
      - run: GOOS=linux GOARCH=amd64 go build -o out/jl cmd/jl/main.go
      - persist_to_workspace:
          root: out
          paths:
            - jl.exe
            - jl
  publish:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: CIRCLE_TAG=$(git tag -l --points-at HEAD)
      - run: echo ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/
      - run: ls -lR
#      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
