# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/jl
    steps:
      - checkout
      - run: mkdir -p workspace/out
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: GOOS=windows GOARCH=amd64 go build -o workspace/out/jl.exe cmd/jl/main.go
      - run: GOOS=linux GOARCH=amd64 go build -o workspace/out/jl cmd/jl/main.go
      - run: echo "export CIRCLE_TAG=$(git tag -l --points-at HEAD)" >> workspace/circle_tag
      - persist_to_workspace:
          root: workspace
          paths:
            - circle_tag
            - out/jl.exe
            - out/jl
  publish:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./workspace
      - run: echo "export CIRCLE_TAG=$(echo ./workspace/circle_tag)" >> $BASH_ENV
      - run: echo ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./workspace/out
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./workspace/out
workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
